### ISSUE TITLE
[wishlist] runbot_prebuild: Main view remove button action (not push option) in "Pick a Team" element

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/odoo-extra#33]
![descarga 5](https://cloud.githubusercontent.com/assets/6644187/7057840/014cb69e-de20-11e4-938b-87b91ccd225a.png)

**Comment by nhomar** [comment]
@moylop260 all team management on frontend was redisigned here https://github.com/Vauxoo/odoo-extra/pull/41 then it becomes this issue ion obsollete.
