### ISSUE TITLE
[8.0] Stickies and manually created pre_builds wrongly ordered

### ISSUE THREAD

**Issue by nhomar** [Vauxoo/odoo-extra#50]
Hello.

Allways we created stickies prebuilds it should be greate oin in the view allways we can see the manually created after the stickies ones.

![orderesd](https://www.evernote.com/shard/s158/sh/1028a8f6-9113-48af-b4e4-481bcf2ca2df/13848b3af50b6144e50b8900ac92a175/deep/0/runbot.repo---localhost.png)

**Comment by moylop260** [comment]
Fixed with new runbot
