### ISSUE TITLE
build link of a pr is not unique

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/odoo-extra#59]
Imagine next pr:
odoo/odoo/pr/1
odoo/odoo-extra/pr/1

Imagine next prebuild:
odoo/odoo, check pr: yes
odoo/odoo-extra, check pr: yes

This will create 2 builds with same link
#pull_1
#pull_1

This should be
#odoo_odoo_pull_1
#odoo_odoo-extra_pull_1

**Comment by moylop260** [comment]
FYI I found a PR of a particular project with this backend search
![builds odoo](https://cloud.githubusercontent.com/assets/6644187/7238229/639f36d8-e766-11e4-93dc-5f31057a284c.png)

**Comment by nhomar** [comment]
which one
"sequence?"

**Comment by moylop260** [comment]
Yes,
You can search your build in front-end with `sequence` or `dest` field.

**Comment by moylop260** [comment]
Fixed with new runbot
