### ISSUE TITLE
Filter of builds on frontend don't work: is ignored

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/odoo-extra#60]

**Comment by moylop260** [comment]
@nhomar 
With ew GUI I don't saw the `search` widget.
Can you help to find it?
![search filter](https://cloud.githubusercontent.com/assets/6644187/7443438/bb291f74-f10f-11e4-8153-f2ec8d594cab.png)

**Comment by nhomar** [comment]
I need add it to the interface..... I remove it just waiting for this feature to work. I can add it again or let you know what you need to add in the interface and where.

**Comment by moylop260** [comment]
Fixed with new runbot
