### ISSUE TITLE
[IMP] Make more straight forward teams on runbot.

### ISSUE THREAD

**Issue by nhomar** [Vauxoo/odoo-extra#62]
Now with the new version, runbot has teams and an admin and user approach.

We created before this, then I think we should homologate that behavior.

![runbotuser](https://www.evernote.com/shard/s158/sh/d186084e-f6ea-4ec3-bf9c-3cbbee2b125a/93c93badf8900b155b781f4a4ac1207d/deep/0/Users---Odoo-y-200px-Flag_of_Venezuela.svg.png-y-1.-Basica-(bash).png)

**Comment by moylop260** [comment]
Fixed with new runbot 9
