### ISSUE TITLE
[ERR] - Incorrect management of build view when builds not found.

### ISSUE THREAD

**Issue by nhomar** [Vauxoo/odoo-extra#64]
Hello.

When some sort of situations approaes the br['builds'] variable is returned with False value, It is important in order to avoid this traceback.

![Bug](https://www.evernote.com/shard/s158/sh/146de7d8-83a4-4db3-9818-23c019c30336/a6c836eb4bdf4447a246c0ae02fda465/deep/0/Internal-Server-Error.png)

**Comment by moylop260** [comment]
@nhomar 
(Force) Fixed here
https://github.com/Vauxoo/odoo-extra/pull/63

**Comment by nhomar** [comment]
@moylop260 Yes but the view should not deliver an error on the render (or do you think it should?)

**Comment by moylop260** [comment]
You are right!
If I delete a prebuild is other case of show this error too

**Comment by moylop260** [comment]
Fixed with new runbot
