### ISSUE TITLE
button kill build from front-end is missed

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/odoo-extra#65]
![kill_build](https://cloud.githubusercontent.com/assets/6644187/7204440/c1bc19b0-e4e7-11e4-893b-14c9df5f5314.png)

**Comment by moylop260** [comment]
@nhomar 
Do you remove this button?
Or is a change of merge from odoo/odoo-extra

**Comment by nhomar** [comment]
I overwrite such view for buttons, probably I didn't ad it. I will chek it.

**Comment by moylop260** [comment]
Maybe is better don't allow show this button directly to final users.
As simple as the original runbot is a good way for now.
