### ISSUE TITLE
Create a database with all modules but without demo data (and without execution of test)

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/odoo-extra#66]
Some cases we need a database without data demo to check that configurator modules is working done!

**Comment by moylop260** [comment]
@nhomar 
What do you think of this feature?

**Comment by nhomar** [comment]
Absolutly agreed.

Then the results of every runbot should be 3 db's?

1.- All demo data and tested.
2.- Only Base but with demo.
3.- One blank DB without demo.?

I think for performance issue it should be necesary "Only in the sticky" Or asked explicitally. but Yes I like the feature.

**Comment by moylop260** [comment]
Fixed here:
https://github.com/Vauxoo/runbot-addons/pull/8/files
