### ISSUE TITLE
[IMP] days to check PR and refs should be configurable.

### ISSUE THREAD

**Issue by nhomar** [Vauxoo/odoo-extra#70]
On this PR.

https://github.com/Vauxoo/odoo-extra/pull/69

@moylop260 add the feature of take just last 30 days of buids, @ruiztulio propose it should be configurable, then I am agreed I create this issue to have control of such feature on future version.

**Comment by moylop260** [comment]
Adding a option of integer field here:
![configure runbot odoo](https://cloud.githubusercontent.com/assets/6644187/7728802/e24a397e-fed6-11e4-90a7-0aec41d42a4f.png)


And replace `datetime.timedelta(30)` by value of this option similar to `datetime.timedelta(VALUE_SETTINGS)` in next files:
[code_datetime.timedelta(30)](https://github.com/Vauxoo/odoo-extra/commit/64bbb6038914c28ab5341a234e2f6c8571c9edaa)

**Comment by hugho-ad** [comment]
@moylop260, this issue can be closed
