### ISSUE TITLE
[IMP] Delete the runbot.prebuild should delete the runbot.builds related "also"

### ISSUE THREAD

**Issue by nhomar** [Vauxoo/odoo-extra#71]
Hello.

If we delete a pre-build it should delete the buils related to it automatically.

![Test](https://www.evernote.com/shard/s158/sh/d22264c2-0493-4741-b625-6b2fb514eaf5/fb03f229b4b87ba63df3427bc5d25e1e/deep/0/Pre-Builds---Odoo.png)

**Comment by moylop260** [comment]
Add to class runbot_build in field m2o prebuild_id a extra parameters `ondelete='cascade'`
