### ISSUE TITLE
[IMP] Sync github status with actual refs/XX branches on runbot.

### ISSUE THREAD

**Issue by nhomar** [Vauxoo/odoo-extra#72]
Hello.

If we delete a branch or close/merge a PR the reference to such PR is not synced with runbot, bringing a lot of processing time of useless tests.

The objective is that if a PR is **closed/merged** then this refs on github repository should be absolutly ignored from future builds.

**Comment by moylop260** [comment]
worked here:
https://github.com/Vauxoo/runbot-addons/pull/9
